extends: conditional
message: "Spell out '%s', unless it is a common abbreviation is common it is not
the first use in this article or topic."
link: 'https://docs.mongodb.com/meta/style-guide/style/abbreviations/'
level: suggestion
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
exceptions:
  - API
  - ASCII
  - BIOS
  - BSON
  - CD
  - CD-ROM
  - CGI
  - CLI
  - CPU
  - CSS
  - CSV
  - DNS
  - DVD
  - FAQ
  - FTP
  - GB
  - GHz
  - GMT
  - GNU
  - GUI
  - GUID
  - HTML
  - HTTP
  - HTTPS
  - ID
  - IEEE
  - IMAP
  - I/O
  - IP
  - JSON
  - KB
  - Kbps
  - KBps
  - kHz
  - KMS
  - LAN
  - LDAP
  - MB
  - MHz
  - NIC
  - NTFS
  - OLE
  - OS
  - PEM
  - PDF
  - PHP
  - POP
  - PROD
  - PSA
  - RAM
  - REST
  - ROM
  - SaaS
  - SGML
  - SMTP
  - SQL
  - SSD
  - SSH
  - SSL
  - TCP
  - TCP/IP
  - TLS
  - TTL
  - URI
  - URL
  - USB
  - USD
  - UTC
  - VLAN
  - WAN
  - XFS
  - XML
  - YAML
  - ZIP
