extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/general-term-guidelines/avoid-obscure-words/'
level: error
ignorecase: true
action:
  name: replace
swap:
  '(?:eg|e\.g\.)[\s,]': for example, such as
  etc: and so on
  '(?:ie|i\.e\.)[\s,]': that is
  as per: according to, by way of
  via: through, by
  '(?:vs\.)[\s,]': versus
  ergo: therefore