extends: substitution
message: "Consider if '%s' makes sense instead of '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/alphabetical-terms/'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  access: see, edit, find, use, or view
  all caps: uppercase
  appendices: appendixes
  application: app
  architected: designed, created, planned
  architects: designs, creates, plans
  argument: option
  at-scale: at scale
  backward slash: backslash
  backward: backwards
  be sure: ensure or verify
  boolean: Boolean
  bottom left: lower left
  bottom right: lower right
  bring up: start/turn on/open
  can not: cannot
  cancelled: canceled
  cancelling: canceling
  catalogue: catalog
  click on: click
  client-server: client/server
  co-locate: colocate
  co-location: colocation
  collocate: colocate
  collocation: colocation
  comprise: consist of/ include/ contain
  computer machine: host
  data base: database
  data center: region
  deinstall: uninstall
  deselect: clear
  desire: want
  desired: wanted, appropriate, required
  different than: different from
  do: perform
  double click: double-click
  double tap: double-tap
  down time: downtime
  drill down: navigate
  drop-down list: list
  drop-down menu: menu
  due to: because of
  e-commerce: ecommerce
  e-mail: email
  ethernet: Ethernet
  FAQs: FAQ
  field: box
  for instance: for example
  forward slash: slash
  free: no charge, no cost
  given: particular/specific/-
  grayed out: dimmed
  guarantee: intend or expect
  guaranteed: intended, expected, guaranteed
  hash sign: number sign
  hash symbol: number sign
  have to: must
  homepage: home page
  indices: indexes
  keep in mind: remember/consider/-
  kick off: start
  kicks off: starts
  like: such as
  logfile: log file
  lower-case: lowercase
  lower-case: lowercase
  make sure: ensure
  matrices: matrixes
  meta-data: metadata
  name space: namespace
  nameserver: name server
  need to: must
  not applicable: NA
  off-line: offline
  off-premise: off-premises
  off premise: off-premises
  off premises: off-premises
  off-site: offsite
  on prem: on-premises
  on-line: online
  on-premise: on-premises
  on premise: on-premises
  on premises: on-premises
  on-site: onsite
  OOTB: out-of-the-box
  PC: computer
  plugin: plug-in
  pop-up: dialog box
  pound sign: number sign
  pound symbol: number sign
  quote marks: quotation marks
  read-write: read/write
  readonly: read-only
  refer to: see
  regular: normal/usual/consistent/evenly spaced
  ReST: REST
  right: upper right/lower right
  roadmap: road map
  scrollbar: scroll bar
  slash mark: slash
  Spam: spam
  standalone: stand-alone
  start up: start
  synch: sync
  synchronize: sync
  time line: timeline
  time stamp: timestamp
  timeframe: time frame
  timezone: time zone
  to architect: to design, to create, to plan
  tool bar: toolbar
  tool box: toolbox
  tool kit: toolkit
  tool tip: tooltip
  top left: upper left
  top right: upper right
  towards: toward
  unselect: clear
  up time: uptime
  up to date: up-to-date
  upper-case: uppercase
  uptodate: up-to-date
  useable: usable
  utilization: usage
  utilize: use
  whitepaper: white paper
  wi-fi: Wi-Fi
  WiFi: Wi-Fi
  wifi: Wi-Fi
  Wifi: Wi-Fi
  wild card: wildcard
  wish: want
  write only: write-only
  zeroes: zeros
  debian: Debian
  fedora: Fedora
  homebrew: Homebrew
  Kubeadm: kubeadm
  Kubectl: kubectl
  Kubelet: kubelet
  kubernetes: Kubernetes
  Kube Controller Manager: kube-controller-Manager
  Kube Proxy: kube-proxy
  Kube Scheduler: kube-scheduler