extends: existence
message: "Avoid the subjunctive '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/writing/write-to-the-user/#avoid-the-subjunctive-mood'
ignorecase: true
level: error
scope: sentence
nonword: true
tokens:
  - '\bwould\b'
  - '\ncould\b'
  - '\bshould\b'
