extends: existence
message: "Use accessible only to refer to things that all people, including those with disabilities, can easily use. Don’t use it to mean simple or open."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/alphabetical-terms/'
level: error
ignorecase: false
nonword: false
tokens:
  - accessible