extends: existence
message: "Don't use '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/alphabetical-terms/'
ignorecase: true
level: error
tokens:
  - abortion
  - and/or
  - and so on
  - slash mark
  - billion
  - biweekly
  - bimonthly
  - front end
  - front-end
  - if necessary
  - respectively
  - trillion
