# Based on: https://gitlab.com/gitlab-org/gitlab/-/tree/master/doc/.vale/gitlab
extends: existence
message: 'Avoid using future tense where possible.'
ignorecase: true
level: warning
link: 'https://docs.mongodb.com/meta/style-guide/writing/use-present-tense/'
raw:
  - "(going to( |\n|[[:punct:]])[a-zA-Z]*|"
  - "will( |\n|[[:punct:]])[a-zA-Z]*|"
  - "won't( |\n|[[:punct:]])[a-zA-Z]*|"
  - "[a-zA-Z]*'ll( |\n|[[:punct:]])[a-zA-Z]*)"