extends: existence
message: "Avoid making claims as to supported software unless we are
tracking how this software evolves."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/alphabetical-terms/'
level: suggestion
ignorecase: false
nonword: true
tokens:
  - supported