extends: existence
message: 'Avoid using past tense where possible: "%s".'
ignorecase: true
level: suggestion
link: 'https://docs.mongodb.com/meta/style-guide/writing/use-present-tense/'
scope: sentence
tokens:
  - abode
  - arisen
  - arose
  - ate
  - awoke
  - awoken
  - bade
  - beaten
  - became
  - become
  - been
  - began
  - begun
  - bent
  - bid
  - bidden
  - bitten
  - bled
  - blown
  - bore
  - born
  - bought
  - broke
  - broken
  - brought
  - built
  - came
  - caught
  - chose
  - chosen
  - dealt
  - did
  - did
  - done
  - drank
  - drawn
  - drew
  - driven
  - drove
  - drunk
  - eaten
  - fallen
  - fed
  - fell
  - felt
  - flew
  - flown
  - forgot
  - forgotten
  - fought
  - found
  - froze
  - frozen
  - gave
  - given
  - gone
  - got
  - gotten
  - grew
  - grown
  - had
  - heard
  - held
  - hid
  - hidden
  - hung
  - kept
  - knew
  - known
  - laid
  - lain
  - lay
  - led
  - left
  - lent
  - lit
  - lost
  - lost
  - made
  - meant
  - met
  - paid
  - ran
  - rang
  - ridden
  - risen
  - rode
  - rose
  - rung
  - said
  - sang
  - sank
  - sat
  - saw
  - seen
  - sent
  - shaken
  - shone
  - shook
  - shot
  - showed
  - shown
  - slept
  - slid
  - sold
  - spent
  - spoke
  - spoken
  - sprang
  - sprung
  - stole
  - stolen
  - stood
  - stuck
  - sung
  - sunk
  - swam
  - swept
  - swore
  - sworn
  - swum
  - swung
  - taken
  - taught
  - thought
  - threw
  - thrown
  - told
  - took
  - tore
  - torn
  - understood
  - was
  - went
  - were
  - woke
  - woken
  - won
  - wore
  - worn
  - wove
  - woven
  - written
  - wrote
  - burnt
  - burned
  - could
  - dived
  - dove
  - dreamt
  - dreamed
  - forbade
  - forbidden
  - leant
  - leaned
  - learnt
  - proved
  - proven
  - sought
  - shone
  - sped
  - spelt
  - spun
  - stood
  - stung
  - struck
  - stricken
  - strove
  - striven
  - swelled
  - swollen
  - underwent
  - undergone
  - withdrew
  - withdrawn
