# Based on: https://github.com/errata-ai/proselint/blob/master/proselint/But.yml

extends: existence
message: "Do not start a paragraph with a 'but'."
level: suggestion
scope: paragraph
action:
  name: remove
tokens:
  - ^But