extends: existence
message: "Verify your usage of '%s' with the Alphabetical List of Terms in the style guide."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/alphabetical-terms/'
level: suggestion
ignorecase: true
tokens:
  - 'on'
  - above
  - affect
  - allow
  - among
  - assure
  - before
  - below
  - between
  - both
  - box
  - button
  - check
  - choose
  - client
  - close
  - complement
  - complete
  - compliment
  - computer
  - default
  - disabled
  - display
  - do
  - drag-and-drop
  - drop-down
  - earlier
  - effect
  - either
  - enable
  - ensure
  - error
  - exit
  - fewer
  - following
  - given
  - gray
  - grayed
  - grayed out
  - higher
  - if necessary
  - impact
  - insure
  - interface
  - later
  - less
  - let
  - lets
  - leverage
  - log in
  - log off
  - login
  - logoff
  - lower
  - machine
  - machine
  - man
  - menu item
  - mouse
  - percent
  - percentage
  - permissions
  - permit
  - please
  - pop-up
  - preceding
  - press
  - prior
  - privileges
  - quit
  - rights
  - stop
  - unavailable
  - whether