extends: existence
message: "Don’t use a comma to set off a restrictive clause (one that begins with that)."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#commas'
ignorecase: true
level: error
nonword: true
tokens:
  - ', that'
