extends: existence
message: "Use a comma to set off a nonrestrictive clause (one that begins with which)."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/'
ignorecase: true
level: suggestion
nonword: true
tokens:
  - '(\w{1,}) which'
