extends: existence
message: "When a comma is required after a quotation that’s embedded in text, place the comma inside the closing quotation mark."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#commas'
level: suggestion
scope: text
nonword: true
tokens:
  - '(“\w*”),'
  - '("\w*"),'
  - '["“][^"”“]+["”][.,]'
  - '"[^"]+"[.,?]'