# Based on: https://github.com/errata-ai/Microsoft/blob/master/Microsoft/OxfordComma.yml

extends: existence
message: "Use the Oxford comma in '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#commas'
level: error
nonword: true
tokens:
  - '(?:[^\s,]+,){1,} \w+ (?:and|or) \w+[.?!]'
  - '(?:[\w-_` ]+,){2,}(?:[\w-_` ]+) (and |or )'