extends: existence
message: "If you can't use specific references, use following or preceding to reference an item in text or copy."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/general-term-guidelines/use-consistent-time-references/'
nonword: false
level: suggestion
tokens:
  - '(above(,|.))'
  - '(below(,|.))'
  - '(before(,|.))'
  - '(after(,|.))'
