extends: existence
message: "To refer to product releases, use earlier or later."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/general-term-guidelines/use-consistent-time-references/'
nonword: false
level: error
tokens:
  - '(MongoDB \d.\d.* (higher|lower|above|below|older|newer))'
  - '((higher|lower|above|below|older|newer).*MongoDB \d.\d)'
