extends: substitution
message: "Feel free to use '%s' instead of '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/contractions/'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  it is: it's
  that is: that's
  there is: there's
  they are: they're
  you are: you're
  that is: that's
  we are: we're
  we have: we've
