extends: substitution
message: "Feel free to use '%s' instead of '%s', unless you mean to
emphasize the negative."
link: 'https://docs.mongodb.com/meta/style-guide/style/contractions/'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  are not: aren't
  cannot: can't
  did not: didn't
  does not: doesn't
  do not: don't
  is not: isn't
  was not: wasn't
  were not: weren't
  will not: won't
  would not: wouldn't
  could not: couldn't
  has not: hasn't
  have not: haven't
  should not: shouldn't
