# Based on: https://github.com/errata-ai/Google/blob/master/Google/EnDash.yml
extends: existence
message: "Use an em dash ('—') instead of '–' unless this is a compound word."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#dashes'
nonword: true
level: suggestion
action:
  name: edit
  params:
    - replace
    - '-'
    - '—'
tokens:
  - '–'