# Based on: https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Dashes.yml
extends: existence
message: "Remove whitespace around '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#dashes'
ignorecase: true
scope: sentence
nonword: true
level: suggestion
action:
  name: edit
  params:
    - remove
    - ' '
tokens:
  - '[—–]\s|\s[—–]'