extends: existence
message: "Do not use a comma before and after the year '%s' when only
the month and year are embedded in a sentence unless the syntax would
ordinarily require a comma following the year."
link: 'https://docs.mongodb.com/meta/style-guide/style/dates/'
ignorecase: true
level: suggestion
nonword: true
tokens:
  - '(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?), \d{4}'
  - '(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?) \d{4},'