# Based on: https://github.com/errata-ai/Microsoft/blob/master/Microsoft/DateFormat.yml
extends: existence
message: "Unless space is limited, use 'November 12, 2010' format, not '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/dates/'
ignorecase: true
level: suggestion
nonword: true
tokens:
  - ' \d{1,2}/\d{1,2}/(\d{2}|\d{4})'
  - ' \d{1,2}\.\d{1,2}\.(\d{2}|\d{4})'
  - ' \d{1,2} (?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?) (\d{2}|\d{4})'
  - ' \d{1,2} (?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?), (\d{2})'