extends: existence
message: "Use an ellipsis (…) only in syntax or to indicate omitted code in code examples."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#ellipses'
nonword: true
level: suggestion
action:
  name: remove
tokens:
  - '\.\.\.'