extends: conditional
message: "Use @example.com or @example.org as the domain name for example
email addresses instead of '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/email-addresses/'
level: suggestion
ignorecase: false
# This is a hack to allow us to make use of exceptions.
first: '@\w*\.\w*\b'
second: '@\w*\.\w*\b'
# ... with the exception of these:
exceptions:
  - '@example.com'
  - '@example.org'