extends: substitution
message: "Consider using '%s' instead of the oppressive language '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/terms-for-global-audience/#use-non-oppressive-language'
level: warning
ignorecase: true
action:
  name: replace
swap:
  black hat: unethical
  'blacklist(?:ed|ing)?': access list, blocklist, denylist, exclude list, remove, deny, block
  master: primary, active, coordinator, accomplish
  slave: secondary, standby, subordinate, replica, worker, subordinate
  white hat: ethical
  whitelist: access list, allow list, allowed list, add, allow, permit
