extends: substitution
message: "Use '%s' instead of the idiom/colloquialism '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/terms-for-global-audience/#don-t-use-idioms-or-colloquialisms'
level: warning
ignorecase: true
action:
  name: replace
swap:
  for the most part: generally
  bear in mind, keep in mind: consider, remember
  keep an eye out for: look for
  figure out: determine
  stand for: represent
  come across: encounter
  fine tune: refine, customize
  get a feel for: become familiar with
  in light of: because of
  set aside: defer, allocate
  kind of like: similar to
  lots of: many
  what's more: moreover
  a hair smaller than: slightly smaller than
  when you're done: when you're finished
