extends: substitution
message: "Consider using '%s' instead of the jargon '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/terminology/terms-for-global-audience/#use-jargon-with-care'
level: error
ignorecase: true
action:
  name: replace
swap:
  abort: stop, end, cancel, exit
  boot: start
  reboot: restart
  bounce: restart
  cache: place in cache
  debug: resolve
  dropped: discontinued
  dummy: placeholder, sample, fake
  execute: run
  fire up: start
  freeze: stop responding
  grayed: unavailable, dimmed
  grayed out: unavailable, dimmed
  hang: stop responding
  interface: connect, communicate, interact
  kill: cancel, stop, end, terminate
  launch: start
  ping: contact, alert
  sanity (?:check|test): test, evaluate
  spin up: create
  throw: generate
