extends: existence
message: "IPv6 addresses should use colons (:) as separators ('%s')."
link: 'https://docs.mongodb.com/meta/style-guide/style/ip-addresses/'
level: suggestion
nonword: true
tokens:
  - '(((([[:xdigit:]]{4}(\.|:)){7})([[:xdigit:]]{4}){1})(/\d+)?)'