extends: substitution
message: "Use %s instead of the contraction '%s' to avoid confusion."
link: 'https://docs.mongodb.com/meta/style-guide/style/contractions/'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  let's: let us
  how's: how is
  what's: what is
  when's: when is
  where's: where is
  who's: who is
  why's: why is
  mustn’t: must not
  mightn’t: might not
  shouldn't: should not
  should’ve: should have
  could’ve: could have
  that’ll: that will
  MongoDB's: X of MongoDB
