extends: existence
message: "Don’t hyphenate words like '%s' unless it’s necessary to avoid confusion."
link: https://docs.mongodb.com/meta/style-guide/terminology/alphabetical-terms/
ignorecase: true
level: suggestion
action:
  name: convert
  params:
    - simple
tokens:
  - 'auto-\w+'
  - 'anti-\w+'
  - 'bi-\w+'
  - 'co-\w+'
  - 'inter-\w+'
  - 'multi-\w+'
  - 'non-\w+'
  - 'post-\w+'
  - 'pre-\w+'
  - 're-\w+'
  - 'sub-\w+'
  - 'un-\w+'