extends: existence
message: "Unless space is limited, use either 'from 10 to 20 diagrams' or
'between 2010 and 2020' instead of '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/style/numbers/'
ignorecase: true
level: suggestion
scope: sentence
nonword: true
tokens:
  - '(\b(\d{1,})–(\d{1,})\b)'
  - '(\b(\d{1,})-(\d{1,})\b)'
  - '\b\d+\s?[-–]\s?\d+\b'
