extends: existence
message: "Don’t use the word inclusive in your description ('%s')."
link: 'https://docs.mongodb.com/meta/style-guide/style/numbers/'
ignorecase: true
level: error
nonword: true
tokens:
  - 'through .*, inclusive'
