# Based on: https://github.com/d2s/dot/blob/337dbb629d31e42d79f78266d7b5d6e7a4e0f7f1/ci/vale/styles/Microsoft/Ordinal.yml

extends: existence
message: "Don't add -ly to an ordinal number."
level: error
action:
  name: edit
  params:
    - trim
    - ly
tokens:
  - firstly
  - secondly
  - thirdly