extends: existence
message: "Avoid parentheses in running text unless you are showing an
abbreviation, a special character, examples, or a concise phrase that
qualifies a term, title, or step ('%s')."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#parentheses'
nonword: true
level: suggestion
tokens:
  - '\(.+\)'