extends: existence
message: "Use a space, not a dash or parentheses, to separate parts of the
telephone number. Precede phone numbers with the applicable country code
('%s')."
link: 'https://docs.mongodb.com/meta/style-guide/style/telephone-numbers/'
nonword: true
level: suggestion
tokens:
  - '((((\d{1})|(\d{3}))-){2,3}\d{3,4})'
  - '((\d| )*(\(\d+\))( |-)(\d{3,})(\d{3,}| |-){1,})'
