extends: existence
message: "Avoid negative statements where possible ('%s')."
link: 'https://docs.mongodb.com/meta/style-guide/writing/use-positive-statements/'
ignorecase: true
level: warning
nonword: true
tokens:
  - didn't
  - did not
  - don't
  - do not
  - doesn't
  - does not
  - won't
  - will not
  - wouldn't
  - would not
  - shouldn't
  - should not
  - couldn't
  - could not
  - am not
  - isn't
  - is not
  - aren't
  - are not
