extends: existence
message: "Avoid using semicolons, which are often misused and, even when used correctly, can make sentences longer and more difficult to understand."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#semicolons'
nonword: true
level: suggestion
tokens:
  - ';'