# Based on https://github.com/testthedocs/OpenStack/blob/master/OpenStack/Setup.yml

extends: substitution
message: Use %s instead of “%s”
level: suggestion
# Use 'setup' (noun) or 'set up' (verb).
pos: 'setup/VB|set/NN up/\w+|set-up/\w+'
ignorecase: true
swap:
  setup: "“set up”"
  set up: "“setup”"
  set-up: "“set up” or “setup”"
