# Based on: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/Simplicity.yml

extends: existence
message: 'Avoid words like "%s" that imply ease of use.'
level: error
ignorecase: true
tokens:
  - easy
  - easily
  - handy
  - simple
  - simply
  - useful
  - obviously
