extends: conditional
message: "Don’t use a slash mark (/) to present a choice among, or a
series of, actions or objects ('%s'). Rewrite the phrase to eliminate the
slash mark."
link: 'https://docs.mongodb.com/meta/style-guide/style/punctuation/#slashes'
level: suggestion
ignorecase: true
# This is a hack to allow us to make use of exceptions.
first: '(\s|^)\w+/\w+(\s)'
second: '(\s|^)\w+/\w+(\s)'
# ... with the exception of these:
exceptions:
  - read/write
  - client/server
