# Based on: https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Spacing.yml
extends: existence
message: "'%s' should have one space."
level: suggestion
nonword: true
tokens:
  - '[a-z][.?!] {2,}[A-Z]'
  - '[a-z][.?!][A-Z]'