# Based on https://github.com/errata-ai/Google/blob/master/Google/Gender.yml
extends: existence
message: "Use singular they instead of '%s'."
link: 'https://docs.mongodb.com/meta/style-guide/writing/use-gender-neutral-pronouns/'
level: error
ignorecase: true
tokens:
  - he/she
  - s/he
  - \(s\)he