# Based on: https://github.com/errata-ai/Google/blob/master/Google/AMPM.yml

extends: existence
message: Use uppercase letters for abbreviations of ante meridiem (AM)
         and post meridiem (PM). Separate these abbreviations from the time with
         a space. Do not use periods in the abbreviations. ('%s')
link: 'https://docs.mongodb.com/meta/style-guide/style/time/'
level: error
nonword: true
tokens:
  - '\d{1,2}[AP]M'
  - '\d{1,2} ?[ap]m'
  - '\d{1,2} ?[aApP]\.[mM]\.'
