extends: existence
message: Show the hours, minutes, and seconds with two digits each, even
         if the leading digit is 0 ('%s').
link: 'https://docs.mongodb.com/meta/style-guide/style/time/#hour-clock'
level: error
nonword: true
tokens:
  - '(\b\d(:[0-5]\d|:\d)+)'
  - '(\b[0-2]\d:\d:(\d+))'
  - '(\b[0-2]\d:[0-5]\d:\d\b)'
