extends: existence
message: If you need to show a time zone ('%s'), use Coordinated Universal Time (UTC), and indicate the time-zone offset from UTC.
link: 'https://docs.mongodb.com/meta/style-guide/style/time/#hour-clock'
level: suggestion
nonword: true
tokens:
  - '(([0-2]\d(:[0-5]\d)+) (\(?[^U(][^T][^C])( ?(-\d+)?)?(\)?))'