extends: existence
message: Avoid using the article “%s as the first word in a heading.”
link: 'https://docs.mongodb.com/meta/style-guide/style/titles-and-headings/'
level: error
scope: heading
tokens:
  - '^(?:a|an|the).+'