# Based on: https://github.com/errata-ai/Google/blob/master/Google/Units.yml

extends: existence
message: "Put a nonbreaking space between the number and the unit in '%s'."
nonword: true
level: warning
tokens:
  - \d+(?:B|kB|MB|GB|TB)
  - \d+(?:ns|ms|s|min|h|d)