name = "drivers"
title = "MongoDB Drivers"

toc_landing_pages = ["/python", "/php", "/java-drivers", "/use-cases"]

intersphinx = [ "https://docs.mongodb.com/master/objects.inv"]

[constants]
version = 4.0
package-name-org = "docs-ecosystem"
pgp-version = "{+version+}"
csharp-docs-versioned = "https://mongodb.github.io/mongo-csharp-driver/2.14"
