name = "drivers"
title = "MongoDB Drivers"

toc_landing_pages = ["/python", "/php", "/java-drivers", "/use-cases"]

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
package-name-org = "docs-ecosystem"
stable-api = "Stable API"

csharp-version = "2.18"
csharp-docs-versioned = "https://mongodb.github.io/mongo-csharp-driver/{+csharp-version+}"

java-version = "4.9"
java-api = "https://mongodb.github.io/mongo-java-driver/{+java-version+}"

[[banners]]
targets = ["csharp.txt"]

variant = "tip"
value = """ \
    A new version of the .Net/C# driver documentation is now live. To learn more about using \
    the driver in your application, see the `official MongoDB C# driver documentation \
    <https://www.mongodb.com/docs/drivers/csharp/current/>`__.
    """
