name = "drivers"
title = "MongoDB Drivers"

toc_landing_pages = ["/python", "/php", "/java-drivers", "/use-cases"]

[constants]
version = 4.0
package-name-org = "docs-ecosystem"
pgp-version = "{+version+}"
