name = "drivers"
title = "MongoDB Drivers"

toc_landing_pages = ["/python", "/php", "/java-drivers", "/kotlin-drivers", "/use-cases", "/ruby"]

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
package-name-org = "docs-ecosystem"
stable-api = "Stable API"
node-driver-long = "MongoDB Node.js Driver"
node-driver-short = "Node.js Driver"

java-version = "4.11"
java-version-full = "{+java-version+}.0"
java-api = "https://mongodb.github.io/mongo-java-driver/{+java-version+}"
